- file:
    path: "/tmp/nvm"
    state: directory

- get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh
    checksum: sha256:0b0606db84327e7ed1b134c1bf57f78531690bb653846ab328a040d31e31fa59
    dest: "/tmp/nvm/install.sh"

- script: /tmp/nvm/install.sh

- shell: source ~/.nvm/nvm.sh && nvm install {{ nodejs_version }}

- file:
    path: "/tmp/nvm"
    state: absent
